# Generated by Django 4.1.1 on 2022-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
                ('companhiaAerea', models.CharField(max_length=100)),
                ('aeroportoTrabalho', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('idVoo', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoVoo', models.IntegerField(max_length=100)),
                ('companhiaAerea', models.CharField(max_length=100)),
                ('partidaprevisao', models.DateTimeField()),
                ('partidaOficial', models.DateTimeField(null=True)),
                ('chegadaPrevisao', models.DateTimeField()),
                ('chegadaOficial', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('rota', models.CharField(max_length=100, null=True)),
                ('aeroportoOrigem', models.CharField(max_length=100)),
                ('aeroportoDestino', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'voos',
            },
        ),
    ]
