# Generated by Django 4.1.3 on 2022-11-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('companhiaAerea', models.CharField(max_length=100, null=True)),
                ('aeroportoTrabalho', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('codigoVoo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('companhiaAerea', models.CharField(max_length=100)),
                ('partidaPrevista', models.DateTimeField()),
                ('partidaReal', models.DateTimeField(null=True)),
                ('chegadaPrevista', models.DateTimeField()),
                ('chegadaReal', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('rota', models.CharField(max_length=100, null=True)),
                ('aeroportoOrigem', models.CharField(max_length=100)),
                ('aeroportoDestino', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'voos',
            },
        ),
    ]
