# Generated by Django 4.1.2 on 2022-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='codigoVoo',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
