# Generated by Django 4.1.3 on 2022-11-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0002_alter_voo_codigovoo_alter_voo_idvoo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voo',
            name='idVoo',
        ),
    ]
