# Generated by Django 4.1.3 on 2022-11-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroporto', '0003_remove_voo_idvoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
